"""Build a file-level provenance matrix for the platform.

Nothing may be released until each file is classified by origin. The evidence
here is the authorship header each file carries, which is weak evidence on its
own -- a header can be inherited by copy-and-edit -- so every file is reported
with the header verbatim rather than silently bucketed, and files with no header
are listed as UNDETERMINED rather than assumed original.

This produces the input to legal review. It is not itself a legal conclusion.

    python build_provenance_matrix.py        # writes PROVENANCE-MATRIX.md
"""

from __future__ import annotations

import os
import pathlib
import re
import sys

PLATFORM = pathlib.Path(
    r"C:\Users\abdul\Downloads\Explainable-AI-Platform-for-GNNs-master"
    r"\Explainable-AI-Platform-for-GNNs-master")
SKIP = {"venv", "__pycache__", "node_modules", ".git", "dist_submission",
        "data", "models", "reports", "experiment_results", "review_artifacts"}

AUTHOR = re.compile(r":author:\s*(.+)")
COPYRIGHT = re.compile(r":copyright:\s*(.+)")


def classify(author: str | None, copyright_: str | None) -> str:
    a = (author or "").lower()
    c = (copyright_ or "").lower()
    if "hci-kdd" in c or "saranti" in a or "holzinger" in a or "pfeifer" in a:
        return "UPSTREAM (HCI-KDD header)"
    if "abdul" in a or "bishara" in a:
        return "CLAIMED ORIGINAL"
    return "UNDETERMINED"


OUT = pathlib.Path(__file__).with_name("PROVENANCE-MATRIX.md")


def main() -> int:
    out: list[str] = []

    def emit(line: str = "") -> None:
        out.append(line)

    rows = []
    for root, dirs, files in os.walk(PLATFORM):
        dirs[:] = [d for d in dirs if d not in SKIP and not d.startswith(".")]
        for fn in files:
            if not fn.endswith((".py", ".js", ".jsx", ".ts", ".tsx")):
                continue
            p = pathlib.Path(root) / fn
            try:
                head = p.read_text(encoding="utf-8", errors="replace")[:2000]
            except OSError:
                continue
            a = AUTHOR.search(head)
            c = COPYRIGHT.search(head)
            rows.append((
                str(p.relative_to(PLATFORM)).replace("\\", "/"),
                classify(a.group(1) if a else None, c.group(1) if c else None),
                (a.group(1).strip() if a else ""),
                (c.group(1).strip() if c else ""),
            ))

    rows.sort(key=lambda r: (r[1], r[0]))
    counts: dict[str, int] = {}
    for _, k, _, _ in rows:
        counts[k] = counts.get(k, 0) + 1

    emit("# File-level provenance matrix\n")
    emit("Generated by `build_provenance_matrix.py` from authorship headers in "
          "the platform tree.\n")
    emit("**This is evidence for legal review, not a legal conclusion.** A "
          "header records what someone typed, not what was copied. Files marked "
          "CLAIMED ORIGINAL still require diff review against the upstream "
          "`GNN_Counterfactuals` tree before any of them is released, because a "
          "file can be original in header and derivative in substance.\n")
    emit("| Classification | Files |\n|---|---:|")
    for k, v in sorted(counts.items()):
        emit(f"| {k} | {v} |")
    emit(f"| **Total** | **{len(rows)}** |\n")

    emit("## Per file\n")
    emit("| File | Classification | `:author:` | `:copyright:` |")
    emit("|---|---|---|---|")
    for path, k, a, c in rows:
        emit(f"| `{path}` | {k} | {a or '—'} | {c or '—'} |")

    emit("\n## Required before any release\n")
    emit("1. Diff every CLAIMED ORIGINAL file against the corresponding file in "
          "`asaranti/GNN_Counterfactuals` at the commit the fork was taken from, "
          "and record the similarity.")
    emit("2. Resolve every UNDETERMINED file to an origin.")
    emit("3. Establish whether GNN-SubNet code is incorporated, or whether only "
          "its data is used, because the GPL obligation differs between the two.")
    emit("4. Obtain written clearance from the institution's legal or "
          "technology-transfer office covering the specific release "
          "configuration proposed.")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="")
    print(f"wrote {OUT.name}: {len(rows)} files classified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
